/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/member/**/*.{js,jsx}',
    './src/home/**/*.{js,jsx}',
    './src/shared/**/*.{js,jsx}',
  ],
  // Existing pages (FormPage, AdminDashboard, AdminGate) use plain CSS in
  // App.css. Preflight is disabled so Tailwind's base reset never touches
  // their markup — Tailwind only applies to files under src/member and
  // src/home.
  corePlugins: {
    preflight: false,
  },
  theme: {
    extend: {
      colors: {
        background: '#f7f9fb',
        'surface-container-low': '#f2f4f6',
        'on-error-container': '#93000a',
        outline: '#76777d',
        surface: '#f7f9fb',
        'surface-variant': '#e0e3e5',
        primary: '#000000',
        'on-tertiary-fixed': '#002113',
        'surface-tint': '#565e74',
        'primary-container': '#131b2e',
        'on-secondary-fixed': '#0b1c30',
        'surface-bright': '#f7f9fb',
        'on-secondary-fixed-variant': '#38485d',
        'error-container': '#ffdad6',
        'inverse-primary': '#bec6e0',
        'inverse-surface': '#2d3133',
        'surface-container-high': '#e6e8ea',
        'on-secondary-container': '#54647a',
        'tertiary-fixed-dim': '#4edea3',
        'on-tertiary-container': '#009668',
        'surface-container': '#eceef0',
        'secondary-container': '#d0e1fb',
        'surface-container-lowest': '#ffffff',
        'tertiary-container': '#002113',
        'on-error': '#ffffff',
        'on-primary-fixed': '#131b2e',
        'on-background': '#191c1e',
        'secondary-fixed': '#d3e4fe',
        tertiary: '#000000',
        'on-secondary': '#ffffff',
        error: '#ba1a1a',
        'on-tertiary-fixed-variant': '#005236',
        'on-primary-fixed-variant': '#3f465c',
        'on-surface': '#191c1e',
        secondary: '#505f76',
        'on-primary-container': '#7c839b',
        'on-primary': '#ffffff',
        'tertiary-fixed': '#6ffbbe',
        'surface-dim': '#d8dadc',
        'primary-fixed-dim': '#bec6e0',
        'secondary-fixed-dim': '#b7c8e1',
        'on-surface-variant': '#45464d',
        'primary-fixed': '#dae2fd',
        'outline-variant': '#c6c6cd',
        'surface-container-highest': '#e0e3e5',
        'inverse-on-surface': '#eff1f3',
        'on-tertiary': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        unit: '4px',
        'margin-desktop': '40px',
        gutter: '24px',
        'container-max': '1280px',
        'margin-mobile': '16px',
      },
      fontFamily: {
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
